### PR TITLE
Add ESCLocation to the ESCItem in Step by step

### PR DESCRIPTION
**Pull request by StraToN**
And some little fixes

### CODE REVIEW

**Comment by dploeger** [comment]
I added @BHSDuncan as a reviewer here to iron out possible language problems first.

**Review by BHSDuncan — COMMENTED** [review]
A few small edits need to be made but I'll make them as soon as I'm able.

**Review by BHSDuncan — APPROVED** [review]
Made my edits. Looks ok to me now.

**Comment by StraToN** [comment]
Thanks a lot for the fixes!

**Comment by dploeger** [comment]
Oh... I... wasn't ready. 😆 

But yeah, looks fine! Thanks, you two.

**Pull request merged**
